=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/enUS/Assets/rez/UISchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Dialog",
    "description": "A dialog file, converted from RC3, for use in SCR",
    "type": "object",

    "properties": {

        "type": {
            "description": "The type for the parent object. Should always be DIALOG, currently",
            "type": "string"
        },

        "name": {
            "description": "Name of the dialog (should match its filename prefix)",
            "type": "string"
        },

        "rect": {
            "description": "Specification of the dialog's size. Of the form [xMin,yMin,width,height]",
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
                "type": "number"
            }
        },

        "style": {
            "description": "Flags for the dialog's style during in-game display",
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU","WS_BORDER"]
            }
        },

        "children": {
            "description": "A list of child dlg objects",
            "type": [ "array", "null" ],
            "items": {
                "type": "object",
                "properties" : {
                    "type": {
                        "description": "The type of dialog object",
                        "type": "string",
                        "enum": ["DEFPUSHBUTTON", "PUSHBUTTON", "RADIOBUTTON", "CHECKBOX", "LTEXT", "CTEXT", "RTEXT", "LISTBOX", "COMBOBOX", "SCROLLBAR", "EDITTEXT", "RECT", "FLCBTN", "WEBBROWSER", "TEXTBOX", "HOTBOX", "FLC"]
                    },
                    "content": {
                        "description": "A string with anything to be displayed, in-game called pszText",
                        "type": "string"
                    },
                    "id": {
                        "description": "An identifier, hopefully unique, for this dlg object",
                        "type": "number"
                    },
                    "rect": {
                        "description": "Specification of the dialog's size. Of the form [xMin,yMin,width,height]",
                        "type": "array",
                        "minItems": 4,
                        "maxItems": 4,
                        "items": {
                            "type": "number"
                        }
                    },
                    "flags": {
                        "description": "Flags for this dialog in-game",
                        "type": ["array", "null"],
                        "items": {
                            "type": "string",
                            "enum": ["RC_SMALLTEXT", "RC_BIGTEXT", "RC_BIGGERTEXT", "RC_TEXTKERN", "RC_NO_TEXTKERN", "RC_ANCHOR_TOPRIGHT", "RC_ANCHOR_CENTER", "RC_POPUP_BACKGROUND", "WS_TABSTOP", "WS_VISIBLE", "WS_HOTKEY", "WS_HOTVKEY", "SBS_VERT", "SBS_HORZ", "WS_EX_TRANSPARENT", "DS_ABSALIGN", "DS_SYSMODAL", "DS_LOCALEDIT", "DS_SETFONT", "DS_MODALFRAME", "DS_NOIDLEMSG", "DS_SETFOREGROUND", "WS_OVERLAPPED", "WS_POPUP", "WS_CHILD", "WS_MINIMIZE", "WS_DISABLED", "WS_CLIPSIBLINGS", "WS_CLIPCHILDREN", "WS_MAXIMIZE", "WS_CAPTION", "WS_BORDER", "WS_DLGFRAME", "WS_VSCROLL", "WS_HSCROLL", "WS_SYSMENU", "WS_THICKFRAME", "WS_GROUP", "WS_MINIMIZEBOX", "WS_MAXIMIZEBOX", "WS_TILED", "WS_ICONIC", "WS_SIZEBOX", "BS_PUSHBUTTON", "BS_DEFPUSHBUTTON", "BS_CHECKBOX", "BS_AUTOCHECKBOX", "BS_RADIOBUTTON", "BS_3STATE", "BS_AUTO3STATE", "BS_GROUPBOX", "BS_USERBUTTON", "BS_AUTORADIOBUTTON", "BS_OWNERDRAW", "BS_LEFTTEXT", "ES_LEFT", "ES_CENTER", "ES_RIGHT", "ES_MULTILINE", "ES_UPPERCASE", "ES_LOWERCASE", "ES_PASSWORD", "ES_AUTOVSCROLL", "ES_AUTOHSCROLL", "ES_NOHIDESEL", "ES_OEMCONVERT", "ES_READONLY", "ES_WANTRETURN", "SS_RIGHT", "SS_BLACKFRAME", "FLC_LOOP", "FLC_FADEIN", "FLC_FADED", "FLC_MOUSEOVER", "FB_EXCLUSIVE", "FB_PRESSED", "FB_HTEXTLEFT", "FB_HTEXTCENTER", "FB_HTEXTRIGHT", "FB_VTEXTTOP", "FB_VTEXTCENTER", "FB_VTEXTBOTTOM", "CTRL_TRANSLUCENT", "CTRL_ENTER", "CTRL_ESCAPE", "CTRL_BTN_RJUST" ]
                        }
                    },
                    "children": {"$ref": "#/properties/children"}
                }
            }
        }

      }

}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_UA_FILES/locales/ruRU/Assets/rez/gluBattlenetMatchmakingToastScreen.ui.json
{
  "type": "DIALOG",
  "name": "MatchmakingScreen",
  "rect": [0,0,640,480],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "RECT",
      "content": "glue\\create\\twoBtnHolder.dds",
      "id": 1,
      "rect": [384,380,204,100],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\create\\toastMap.dds",
      "id": 3,
      "rect": [0,200,640,220],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT","RC_ANCHOR_CENTER"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\Battlenet\\Chat\\ButtonSmall.dds",
      "id": 4,
      "rect": [35,430,100,20],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluBattlenetMatchmakingToastScreen-1",
      "id": 5,
      "rect": [512,443,112,22],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGGERTEXT","WS_HOTKEY","CTRL_ENTER","CTRL_ESCAPE","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluBattlenetMatchmakingToastScreen-2",
      "id": 6,
      "rect": [388,443,112,22],
      "flags": ["WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","CTRL_ENTER","CTRL_ESCAPE","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluBattlenetMatchmakingToastScreen-3",
      "id": 7,
      "rect": [20,443,112,22],
      "flags": ["WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","CTRL_ENTER","CTRL_ESCAPE","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/ToastPanel/ToastPanel.html",
      "id": 8,
      "rect": [0,0,640,440],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/dlgFatal.ui.json
{
  "type": "DIALOG",
  "name": "dlgFatal",
  "rect": [140,45,360,224],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "DEFPUSHBUTTON",
      "content": "dlgFatal-1",
      "id": -2,
      "rect": [124,159,112,28],
      "flags": ["WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT","CTRL_ENTER"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "dlgFatal-2",
      "id": -10,
      "rect": [10,0,340,92],
      "flags": ["WS_VISIBLE","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "dlgFatal-3",
      "id": -20,
      "rect": [10,92,340,92],
      "flags": ["WS_VISIBLE"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/enUS/Assets/rez/ok.ui.json
{
  "type": "DIALOG",
  "name": "Ok",
  "rect": [176,144,288,128],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU"],
  "children": [
    {
      "type": "DEFPUSHBUTTON",
      "content": "ok-1",
      "id": -2,
      "rect": [92,92,104,28],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "ok-2",
      "id": 1,
      "rect": [12,8,264,80],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/statbtnp.ui.json
{
  "type": "DIALOG",
  "name": "StatBtn",
  "rect": [496,354,144,126],
  "style": [],
  "children": [
    {
      "type": "PUSHBUTTON",
      "content": "statbtnp-1",
      "id": 1,
      "rect": [9,4,36,34],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "statbtnp-2",
      "id": 2,
      "rect": [55,4,36,34],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "statbtnp-3",
      "id": 3,
      "rect": [101,4,36,34],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "statbtnp-4",
      "id": 4,
      "rect": [9,44,36,34],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "statbtnp-5",
      "id": 5,
      "rect": [55,44,36,34],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "statbtnp-6",
      "id": 6,
      "rect": [101,44,36,34],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "statbtnp-7",
      "id": 7,
      "rect": [9,84,36,34],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "statbtnp-8",
      "id": 8,
      "rect": [55,84,36,34],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "statbtnp-9",
      "id": 9,
      "rect": [101,84,36,34],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/gluBattlenetAddFriendPopup.ui.json
{
  "type": "DIALOG",
  "name": "IDD_BATTLENET_ADD_FRIEND_POPUP",
  "rect": [0,0,640,480],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "RECT",
      "content": "",
      "id": -1,
      "rect": [0,0,640,480],
      "flags": ["WS_VISIBLE","RC_POPUP_BACKGROUND"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\Battlenet\\Chat\\ChannelsListPopup\\Bg.dds",
      "id": 10,
      "rect": [140,48,360,384],
      "flags": ["WS_VISIBLE"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/ChatAddFriendPanel/ChatAddFriendPanel.html",
      "id": 11,
      "rect": [140,48,360,384],
      "flags": ["WS_VISIBLE"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/gluModemStatus.ui.json
{
  "type": "DIALOG",
  "name": "ModemStatus",
  "rect": [0,0,288,153],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "LTEXT",
      "content": "",
      "id": 1,
      "rect": [10,15,266,20],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "",
      "id": 2,
      "rect": [21,46,244,20],
      "flags": ["WS_VISIBLE"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluModemStatus-1",
      "id": 3,
      "rect": [85,114,117,23],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","FB_HTEXTCENTER","FB_VTEXTCENTER","CTRL_ESCAPE"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/009_CLEAN_UA/SCR_uaUK/locales/ruRU/Assets/rez/gluGameLobby.ui.json
{
  "type": "DIALOG",
  "name": "Chat",
  "rect": [0,0,640,480],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "RECT",
      "content": "glue\\Chatroom\\pChat.dds",
      "id": 6,
      "rect": [0,308,372,169],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT","RC_ANCHOR_TOPRIGHT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\Chatroom\\pJoin.dds",
      "id": 7,
      "rect": [400,0,240,333],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\Chatroom\\pList.dds",
      "id": 8,
      "rect": [0,0,372,323],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT","RC_ANCHOR_TOPRIGHT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\PalNl\\pCancel.dds",
      "id": 12,
      "rect": [472,356,168,91],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\PalNl\\pOk.dds",
      "id": 11,
      "rect": [436,336,204,71],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluGameLobby-1",
      "id": 9,
      "rect": [441,383,152,22],
      "flags": ["WS_VISIBLE","WS_TABSTOP","CTRL_TRANSLUCENT","RC_BIGGERTEXT","WS_HOTKEY","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluGameLobby-2",
      "id": 10,
      "rect": [477,419,132,22],
      "flags": ["WS_VISIBLE","WS_TABSTOP","CTRL_TRANSLUCENT","RC_BIGGERTEXT","WS_HOTKEY","CTRL_ESCAPE","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/GameLobbyChatPanel/GameLobbyChatPanel.html",
      "id": 1,
      "rect": [26,334,340,140],
      "flags": ["WS_VISIBLE"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/GameSearchMapInfoPanel/GameSearchMapInfoPanel.html",
      "id": 2,
      "rect": [404,53,200,276],
      "flags": ["WS_VISIBLE"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/GameLobbyPanel/GameLobbyPanel.html",
      "id": 3,
      "rect": [30,32,336,284],
      "flags": ["WS_VISIBLE"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/enUS/Assets/rez/dfinale.ui.json
{
  "type": "DIALOG",
  "name": "DFinale",
  "rect": [0,0,320,240],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU"],
  "children": [
    {
      "type": "LTEXT",
      "content": "dfinale-1",
      "id": 1,
      "rect": [20,68,160,108],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP"],
      "children": null
    }
  ]
}
