=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/enUS/Assets/rez/UISchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Dialog",
    "description": "A dialog file, converted from RC3, for use in SCR",
    "type": "object",

    "properties": {

        "type": {
            "description": "The type for the parent object. Should always be DIALOG, currently",
            "type": "string"
        },

        "name": {
            "description": "Name of the dialog (should match its filename prefix)",
            "type": "string"
        },

        "rect": {
            "description": "Specification of the dialog's size. Of the form [xMin,yMin,width,height]",
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
                "type": "number"
            }
        },

        "style": {
            "description": "Flags for the dialog's style during in-game display",
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU","WS_BORDER"]
            }
        },

        "children": {
            "description": "A list of child dlg objects",
            "type": [ "array", "null" ],
            "items": {
                "type": "object",
                "properties" : {
                    "type": {
                        "description": "The type of dialog object",
                        "type": "string",
                        "enum": ["DEFPUSHBUTTON", "PUSHBUTTON", "RADIOBUTTON", "CHECKBOX", "LTEXT", "CTEXT", "RTEXT", "LISTBOX", "COMBOBOX", "SCROLLBAR", "EDITTEXT", "RECT", "FLCBTN", "WEBBROWSER", "TEXTBOX", "HOTBOX", "FLC"]
                    },
                    "content": {
                        "description": "A string with anything to be displayed, in-game called pszText",
                        "type": "string"
                    },
                    "id": {
                        "description": "An identifier, hopefully unique, for this dlg object",
                        "type": "number"
                    },
                    "rect": {
                        "description": "Specification of the dialog's size. Of the form [xMin,yMin,width,height]",
                        "type": "array",
                        "minItems": 4,
                        "maxItems": 4,
                        "items": {
                            "type": "number"
                        }
                    },
                    "flags": {
                        "description": "Flags for this dialog in-game",
                        "type": ["array", "null"],
                        "items": {
                            "type": "string",
                            "enum": ["RC_SMALLTEXT", "RC_BIGTEXT", "RC_BIGGERTEXT", "RC_TEXTKERN", "RC_NO_TEXTKERN", "RC_ANCHOR_TOPRIGHT", "RC_ANCHOR_CENTER", "RC_POPUP_BACKGROUND", "WS_TABSTOP", "WS_VISIBLE", "WS_HOTKEY", "WS_HOTVKEY", "SBS_VERT", "SBS_HORZ", "WS_EX_TRANSPARENT", "DS_ABSALIGN", "DS_SYSMODAL", "DS_LOCALEDIT", "DS_SETFONT", "DS_MODALFRAME", "DS_NOIDLEMSG", "DS_SETFOREGROUND", "WS_OVERLAPPED", "WS_POPUP", "WS_CHILD", "WS_MINIMIZE", "WS_DISABLED", "WS_CLIPSIBLINGS", "WS_CLIPCHILDREN", "WS_MAXIMIZE", "WS_CAPTION", "WS_BORDER", "WS_DLGFRAME", "WS_VSCROLL", "WS_HSCROLL", "WS_SYSMENU", "WS_THICKFRAME", "WS_GROUP", "WS_MINIMIZEBOX", "WS_MAXIMIZEBOX", "WS_TILED", "WS_ICONIC", "WS_SIZEBOX", "BS_PUSHBUTTON", "BS_DEFPUSHBUTTON", "BS_CHECKBOX", "BS_AUTOCHECKBOX", "BS_RADIOBUTTON", "BS_3STATE", "BS_AUTO3STATE", "BS_GROUPBOX", "BS_USERBUTTON", "BS_AUTORADIOBUTTON", "BS_OWNERDRAW", "BS_LEFTTEXT", "ES_LEFT", "ES_CENTER", "ES_RIGHT", "ES_MULTILINE", "ES_UPPERCASE", "ES_LOWERCASE", "ES_PASSWORD", "ES_AUTOVSCROLL", "ES_AUTOHSCROLL", "ES_NOHIDESEL", "ES_OEMCONVERT", "ES_READONLY", "ES_WANTRETURN", "SS_RIGHT", "SS_BLACKFRAME", "FLC_LOOP", "FLC_FADEIN", "FLC_FADED", "FLC_MOUSEOVER", "FB_EXCLUSIVE", "FB_PRESSED", "FB_HTEXTLEFT", "FB_HTEXTCENTER", "FB_HTEXTRIGHT", "FB_VTEXTTOP", "FB_VTEXTCENTER", "FB_VTEXTBOTTOM", "CTRL_TRANSLUCENT", "CTRL_ENTER", "CTRL_ESCAPE", "CTRL_BTN_RJUST" ]
                        }
                    },
                    "children": {"$ref": "#/properties/children"}
                }
            }
        }

      }

}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/gluNewCh.ui.json
{
  "type": "DIALOG",
  "name": "GameName",
  "rect": [0,0,220,100],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU"],
  "children": [
    {
      "type": "FLCBTN",
      "content": "gluNewCh-1",
      "id": 1,
      "rect": [13,75,90,20],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","FB_HTEXTCENTER","FB_VTEXTCENTER","CTRL_ENTER"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluNewCh-2",
      "id": 2,
      "rect": [119,75,90,20],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","FB_HTEXTCENTER","FB_VTEXTCENTER","CTRL_ESCAPE"],
      "children": null
    },
    {
      "type": "EDITTEXT",
      "content": "",
      "id": 3,
      "rect": [13,32,192,20],
      "flags": ["WS_VISIBLE","WS_TABSTOP","WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "gluNewCh-3",
      "id": -1,
      "rect": [4,4,120,20],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_SMALLTEXT"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/009_CLEAN_UA/SCR_uaUK/locales/ruRU/Assets/rez/gluPOk.ui.json
{
  "type": "DIALOG",
  "name": "gluPOk",
  "rect": [0,0,360,200],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU"],
  "children": [
    {
      "type": "FLCBTN",
      "content": "gluPOk-1",
      "id": 1,
      "rect": [103,159,158,29],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","FB_HTEXTCENTER","FB_VTEXTCENTER","CTRL_ENTER"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "gluPOk-2",
      "id": 2,
      "rect": [10,10,340,140],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/009_CLEAN_UA/SCR_uaUK/locales/ruRU/Assets/rez/titledlg.ui.json
{
  "type": "DIALOG",
  "name": "TitleDlg",
  "rect": [0,0,640,480],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "CTEXT",
      "content": "titledlg-1",
      "id": 12,
      "rect": [0,464,640,16],
      "flags": ["WS_VISIBLE","RC_SMALLTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "titledlg-2",
      "id": 1,
      "rect": [220,400,200,20],
      "flags": ["RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\ESRB.dds",
      "id": 3,
      "rect": [4,437,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\GRB-Age.dds",
      "id": 4,
      "rect": [4,437,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\GRB-Violence.dds",
      "id": 10,
      "rect": [84,437,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\PEGI.dds",
      "id": 2,
      "rect": [4,437,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\USK.dds",
      "id": 5,
      "rect": [4,437,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\ESRB.dds",
      "id": 7,
      "rect": [25,425,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\GRB-Age.dds",
      "id": 8,
      "rect": [25,425,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\GRB-Violence.dds",
      "id": 11,
      "rect": [110,425,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\PEGI.dds",
      "id": 6,
      "rect": [25,425,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\USK.dds",
      "id": 9,
      "rect": [25,425,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/009_CLEAN_UA/SCR_uaUK/locales/ruRU/Assets/rez/gluBattlenetToonRegistry.ui.json
{
  "type": "DIALOG",
  "name": "BattlenetToonRegistry",
  "rect": [0,0,640,480],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "RECT",
      "content": "glue\\Battlenet\\ToonRegistry\\ToonListBg.dds",
      "id": 1,
      "rect": [0,0,364,360],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT","RC_ANCHOR_TOPRIGHT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\create\\pInfo.dds",
      "id": 2,
      "rect": [400,0,240,333],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\PalNl\\pCancel.dds",
      "id": 3,
      "rect": [472,356,168,91],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\PalNl\\pOk.dds",
      "id": 4,
      "rect": [436,336,204,71],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluBattlenetToonRegistry-1",
      "id": 5,
      "rect": [441,383,152,22],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGGERTEXT","WS_HOTKEY","CTRL_ENTER","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluBattlenetToonRegistry-2",
      "id": 6,
      "rect": [477,419,132,22],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGGERTEXT","WS_HOTKEY","CTRL_ESCAPE","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluBattlenetToonRegistry-3",
      "id": 7,
      "rect": [46,336,144,20],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGGERTEXT","WS_HOTKEY","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluBattlenetToonRegistry-4",
      "id": 9,
      "rect": [211,336,144,20],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGGERTEXT","WS_HOTKEY","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/RegistrySelectionPanel/RegistrySelectionPanel.html",
      "id": 12,
      "rect": [48,62,308,258],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/RegistryToonInfoPanel/RegistryToonInfoPanel.html",
      "id": 11,
      "rect": [404,53,209,276],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/CreditsScreen.ui.json
{
  "type": "DIALOG",
  "name": "CreditsScreen",
  "rect": [0,0,640,480],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "RECT",
      "content": "glue\\Battlenet\\Credits_A.dds",
      "id": 2,
      "rect": [120,30,420,450],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT","RC_ANCHOR_CENTER"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/CreditsPanel/CreditsPanel.html",
      "id": 1,
      "rect": [0,0,640,480],
      "flags": ["WS_VISIBLE"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/savegame.ui.json
{
  "type": "DIALOG",
  "name": "SaveGame",
  "rect": [128,32,384,256],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU"],
  "children": [
    {
      "type": "EDITTEXT",
      "content": "",
      "id": 2,
      "rect": [32,44,320,18],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "DEFPUSHBUTTON",
      "content": "savegame-1",
      "id": -2,
      "rect": [20,216,104,28],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT","CTRL_ENTER"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "savegame-2",
      "id": 3,
      "rect": [140,216,104,28],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "savegame-3",
      "id": -3,
      "rect": [260,216,104,28],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LISTBOX",
      "content": "",
      "id": 1,
      "rect": [32,70,320,140],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_BORDER","WS_TABSTOP","WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "savegame-4",
      "id": 4,
      "rect": [0,8,384,24],
      "flags": ["WS_CHILD","WS_VISIBLE","RC_BIGGERTEXT"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/gluOptionsPopup.ui.json
{
  "type": "DIALOG",
  "name": "IDD_OPTIONS_POPUP",
  "rect": [0,0,640,480],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "RECT",
      "content": "",
      "id": -1,
      "rect": [0,0,640,480],
      "flags": ["WS_VISIBLE","RC_POPUP_BACKGROUND"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/OptionsPanel/OptionsPanel.html",
      "id": 11,
      "rect": [0,0,640,480],
      "flags": ["WS_VISIBLE"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\GRB-Age.dds",
      "id": 1,
      "rect": [80,285,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\title\\GRB-Violence.dds",
      "id": 2,
      "rect": [80,330,1,1],
      "flags": ["WS_EX_TRANSPARENT"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/gluBattlenetRenameToonPopup.ui.json
{
  "type": "DIALOG",
  "name": "BattlenetRenameToonPopup",
  "rect": [0,0,360,200],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "RECT",
      "content": "glue\\Battlenet\\BlockingOperationPopup.dds",
      "id": 10,
      "rect": [0,0,360,200],
      "flags": ["WS_VISIBLE"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/ToonRenamePanel/ToonRenamePanel.html",
      "id": 11,
      "rect": [0,0,360,200],
      "flags": ["WS_VISIBLE"],
      "children": null
    }
  ]
}
