=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/enUS/Assets/rez/UISchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Dialog",
    "description": "A dialog file, converted from RC3, for use in SCR",
    "type": "object",

    "properties": {

        "type": {
            "description": "The type for the parent object. Should always be DIALOG, currently",
            "type": "string"
        },

        "name": {
            "description": "Name of the dialog (should match its filename prefix)",
            "type": "string"
        },

        "rect": {
            "description": "Specification of the dialog's size. Of the form [xMin,yMin,width,height]",
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
                "type": "number"
            }
        },

        "style": {
            "description": "Flags for the dialog's style during in-game display",
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU","WS_BORDER"]
            }
        },

        "children": {
            "description": "A list of child dlg objects",
            "type": [ "array", "null" ],
            "items": {
                "type": "object",
                "properties" : {
                    "type": {
                        "description": "The type of dialog object",
                        "type": "string",
                        "enum": ["DEFPUSHBUTTON", "PUSHBUTTON", "RADIOBUTTON", "CHECKBOX", "LTEXT", "CTEXT", "RTEXT", "LISTBOX", "COMBOBOX", "SCROLLBAR", "EDITTEXT", "RECT", "FLCBTN", "WEBBROWSER", "TEXTBOX", "HOTBOX", "FLC"]
                    },
                    "content": {
                        "description": "A string with anything to be displayed, in-game called pszText",
                        "type": "string"
                    },
                    "id": {
                        "description": "An identifier, hopefully unique, for this dlg object",
                        "type": "number"
                    },
                    "rect": {
                        "description": "Specification of the dialog's size. Of the form [xMin,yMin,width,height]",
                        "type": "array",
                        "minItems": 4,
                        "maxItems": 4,
                        "items": {
                            "type": "number"
                        }
                    },
                    "flags": {
                        "description": "Flags for this dialog in-game",
                        "type": ["array", "null"],
                        "items": {
                            "type": "string",
                            "enum": ["RC_SMALLTEXT", "RC_BIGTEXT", "RC_BIGGERTEXT", "RC_TEXTKERN", "RC_NO_TEXTKERN", "RC_ANCHOR_TOPRIGHT", "RC_ANCHOR_CENTER", "RC_POPUP_BACKGROUND", "WS_TABSTOP", "WS_VISIBLE", "WS_HOTKEY", "WS_HOTVKEY", "SBS_VERT", "SBS_HORZ", "WS_EX_TRANSPARENT", "DS_ABSALIGN", "DS_SYSMODAL", "DS_LOCALEDIT", "DS_SETFONT", "DS_MODALFRAME", "DS_NOIDLEMSG", "DS_SETFOREGROUND", "WS_OVERLAPPED", "WS_POPUP", "WS_CHILD", "WS_MINIMIZE", "WS_DISABLED", "WS_CLIPSIBLINGS", "WS_CLIPCHILDREN", "WS_MAXIMIZE", "WS_CAPTION", "WS_BORDER", "WS_DLGFRAME", "WS_VSCROLL", "WS_HSCROLL", "WS_SYSMENU", "WS_THICKFRAME", "WS_GROUP", "WS_MINIMIZEBOX", "WS_MAXIMIZEBOX", "WS_TILED", "WS_ICONIC", "WS_SIZEBOX", "BS_PUSHBUTTON", "BS_DEFPUSHBUTTON", "BS_CHECKBOX", "BS_AUTOCHECKBOX", "BS_RADIOBUTTON", "BS_3STATE", "BS_AUTO3STATE", "BS_GROUPBOX", "BS_USERBUTTON", "BS_AUTORADIOBUTTON", "BS_OWNERDRAW", "BS_LEFTTEXT", "ES_LEFT", "ES_CENTER", "ES_RIGHT", "ES_MULTILINE", "ES_UPPERCASE", "ES_LOWERCASE", "ES_PASSWORD", "ES_AUTOVSCROLL", "ES_AUTOHSCROLL", "ES_NOHIDESEL", "ES_OEMCONVERT", "ES_READONLY", "ES_WANTRETURN", "SS_RIGHT", "SS_BLACKFRAME", "FLC_LOOP", "FLC_FADEIN", "FLC_FADED", "FLC_MOUSEOVER", "FB_EXCLUSIVE", "FB_PRESSED", "FB_HTEXTLEFT", "FB_HTEXTCENTER", "FB_HTEXTRIGHT", "FB_VTEXTTOP", "FB_VTEXTCENTER", "FB_VTEXTBOTTOM", "CTRL_TRANSLUCENT", "CTRL_ENTER", "CTRL_ESCAPE", "CTRL_BTN_RJUST" ]
                        }
                    },
                    "children": {"$ref": "#/properties/children"}
                }
            }
        }

      }

}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/enUS/Assets/rez/video.ui.json
{
  "type": "DIALOG",
  "name": "Video",
  "rect": [184,32,264,288],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU"],
  "children": [
    {
      "type": "DEFPUSHBUTTON",
      "content": "video-1",
      "id": -2,
      "rect": [20,252,104,28],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "video-2",
      "id": -3,
      "rect": [140,252,104,28],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "SCROLLBAR",
      "content": "",
      "id": 1,
      "rect": [34,60,208,12],
      "flags": ["SBS_HORZ","WS_CHILD","WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "CHECKBOX",
      "content": "video-3",
      "id": 7,
      "rect": [12,91,240,10],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY"],
      "children": null
    },
    {
      "type": "CHECKBOX",
      "content": "video-4",
      "id": 4,
      "rect": [12,109,240,10],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY"],
      "children": null
    },
    {
      "type": "CHECKBOX",
      "content": "video-5",
      "id": 5,
      "rect": [12,127,240,10],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY"],
      "children": null
    },
    {
      "type": "SCROLLBAR",
      "content": "",
      "id": 6,
      "rect": [34,149,208,12],
      "flags": ["SBS_HORZ","WS_CHILD","WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "RADIOBUTTON",
      "content": "video-6",
      "id": 8,
      "rect": [12,175,240,10],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY"],
      "children": null
    },
    {
      "type": "RADIOBUTTON",
      "content": "video-7",
      "id": 9,
      "rect": [12,199,240,10],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY"],
      "children": null
    },
    {
      "type": "RADIOBUTTON",
      "content": "video-8",
      "id": 10,
      "rect": [12,223,240,10],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "video-9",
      "id": -1,
      "rect": [12,44,208,14],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "video-10",
      "id": -1,
      "rect": [32,74,80,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_SMALLTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "video-11",
      "id": 2,
      "rect": [32,163,80,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_SMALLTEXT"],
      "children": null
    },
    {
      "type": "RTEXT",
      "content": "video-12",
      "id": -1,
      "rect": [166,74,80,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_SMALLTEXT"],
      "children": null
    },
    {
      "type": "RTEXT",
      "content": "video-13",
      "id": 3,
      "rect": [166,163,80,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_SMALLTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "video-14",
      "id": -1,
      "rect": [0,8,264,24],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/009_CLEAN_UA/SCR_uaUK/locales/ruRU/Assets/rez/gluLoad.ui.json
{
  "type": "DIALOG",
  "name": "GameSel",
  "rect": [0,0,640,480],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "RECT",
      "content": "glue\\Load\\pList.pcx",
      "id": 1,
      "rect": [0,0,362,356],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT","RC_ANCHOR_TOPRIGHT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\PalNl\\pCancel.pcx",
      "id": 2,
      "rect": [472,356,168,91],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\PalNl\\pOk.pcx",
      "id": 3,
      "rect": [436,336,204,71],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "gluLoad-1",
      "id": -1,
      "rect": [40,68,136,20],
      "flags": ["WS_VISIBLE","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LISTBOX",
      "content": "",
      "id": 6,
      "rect": [64,92,286,218],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluLoad-2",
      "id": 4,
      "rect": [441,383,152,22],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGGERTEXT","WS_HOTKEY","FB_HTEXTCENTER","FB_VTEXTCENTER","CTRL_ENTER"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluLoad-3",
      "id": 5,
      "rect": [477,419,132,22],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGGERTEXT","WS_HOTKEY","FB_HTEXTCENTER","FB_VTEXTCENTER","CTRL_ESCAPE"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluLoad-4",
      "id": 7,
      "rect": [44,332,164,20],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGGERTEXT","WS_HOTKEY","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_UA_FILES/locales/ruRU/Assets/rez/chathist.ui.json
{
  "type": "DIALOG",
  "name": "ChatHistory",
  "rect": [120,24,400,320],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU"],
  "children": [
    {
      "type": "DEFPUSHBUTTON",
      "content": "chathist-1",
      "id": -2,
      "rect": [150,276,104,28],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT","CTRL_ENTER","CTRL_ESCAPE"],
      "children": null
    },
    {
      "type": "LISTBOX",
      "content": "",
      "id": 1,
      "rect": [16,40,370,220],
      "flags": ["WS_VISIBLE","WS_BORDER","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "chathist-2",
      "id": -1,
      "rect": [54,8,300,20],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/009_CLEAN_UA/SCR_uaUK/locales/ruRU/Assets/rez/gluJoinMultiBattlenet.ui.json
{
  "type": "DIALOG",
  "name": "JoinMultiBattlenet",
  "rect": [0,0,640,480],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "RECT",
      "content": "glue\\create\\pListMap4.dds",
      "id": 1,
      "rect": [0,0,372,356],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT","RC_ANCHOR_TOPRIGHT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\gamesel\\pJoin.dds",
      "id": 2,
      "rect": [400,0,240,333],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\PalNl\\pCancel.dds",
      "id": 3,
      "rect": [472,356,168,91],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\PalNl\\pOk.dds",
      "id": 4,
      "rect": [436,336,204,71],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT"],
      "children": null
    },
    {
      "type": "RECT",
      "content": "glue\\Chatroom\\pChat2.dds",
      "id": 5,
      "rect": [0,308,372,169],
      "flags": ["WS_VISIBLE","CTRL_TRANSLUCENT","RC_ANCHOR_TOPRIGHT"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/GameSearchPanel/GameSearchPanel.html",
      "id": 6,
      "rect": [42,65,330,260],
      "flags": ["WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/GameSearchMapInfoPanel/GameSearchMapInfoPanel.html",
      "id": 7,
      "rect": [404,56,200,272],
      "flags": ["WS_VISIBLE"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "webui/dist/GlobalChatPanel/GlobalChatPanel.html",
      "id": 8,
      "rect": [20,334,344,140],
      "flags": ["WS_VISIBLE"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluJoinMultiBattlenet-1",
      "id": 9,
      "rect": [439,382,155,23],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGGERTEXT","WS_HOTKEY","CTRL_ENTER","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluJoinMultiBattlenet-2",
      "id": 10,
      "rect": [475,417,134,24],
      "flags": ["WS_VISIBLE","WS_TABSTOP","RC_BIGGERTEXT","WS_HOTKEY","CTRL_ESCAPE","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/helpmenu.ui.json
{
  "type": "DIALOG",
  "name": "HelpMenu",
  "rect": [184,32,264,288],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU"],
  "children": [
    {
      "type": "DEFPUSHBUTTON",
      "content": "helpmenu-1",
      "id": -3,
      "rect": [20,252,224,28],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "helpmenu-2",
      "id": 1,
      "rect": [20,36,224,28],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "PUSHBUTTON",
      "content": "helpmenu-3",
      "id": 2,
      "rect": [20,70,224,28],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP","WS_HOTKEY","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "helpmenu-4",
      "id": -1,
      "rect": [0,8,264,24],
      "flags": ["WS_CHILD","WS_VISIBLE","RC_BIGTEXT"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_UA_FILES/locales/ruRU/Assets/rez/gluWebAuthenticationPopup1280.ui.json
{
  "type": "DIALOG",
  "name": "WebAuthenticationPopup",
  "rect": [0,0,250,240],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_BORDER","WS_SYSMENU"],
  "children": [
    {
      "type": "RECT",
      "content": "glue\\Battlenet\\WebAuthenticationPopup\\Bg1280.dds",
      "id": 1,
      "rect": [0,0,250,240],
      "flags": ["WS_VISIBLE"],
      "children": null
    },
    {
      "type": "WEBBROWSER",
      "content": "",
      "id": 4,
      "rect": [5,5,240,230],
      "flags": ["WS_VISIBLE"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "gluWebAuthenticationPopup1280-1",
      "id": 2,
      "rect": [0,0,250,40],
      "flags": [],
      "children": null
    },
    {
      "type": "FLCBTN",
      "content": "gluWebAuthenticationPopup1280-2",
      "id": 3,
      "rect": [200,0,43,33],
      "flags": ["WS_VISIBLE","WS_TABSTOP","CTRL_TRANSLUCENT","RC_BIGGERTEXT","CTRL_ESCAPE","FB_HTEXTCENTER","FB_VTEXTCENTER"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/msnstat4.ui.json
{
  "type": "DIALOG",
  "name": "MsnStat4",
  "rect": [0,0,320,240],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU"],
  "children": [
    {
      "type": "DEFPUSHBUTTON",
      "content": "msnstat4-1",
      "id": -2,
      "rect": [228,224,53,14],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_TABSTOP"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-2",
      "id": 1,
      "rect": [6,14,96,25],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-3",
      "id": 2,
      "rect": [108,14,108,18],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-4",
      "id": 3,
      "rect": [222,14,96,18],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-5",
      "id": 68,
      "rect": [6,4,96,9],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-6",
      "id": 69,
      "rect": [108,4,108,9],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-7",
      "id": 70,
      "rect": [222,4,96,9],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-8",
      "id": 4,
      "rect": [20,74,280,18],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-9",
      "id": 12,
      "rect": [5,60,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-10",
      "id": 20,
      "rect": [50,60,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-11",
      "id": 28,
      "rect": [95,60,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-12",
      "id": 36,
      "rect": [140,60,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-13",
      "id": 44,
      "rect": [185,60,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-14",
      "id": 52,
      "rect": [230,60,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-15",
      "id": 60,
      "rect": [275,60,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-16",
      "id": 5,
      "rect": [20,117,280,18],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-17",
      "id": 13,
      "rect": [5,103,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-18",
      "id": 21,
      "rect": [50,103,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-19",
      "id": 29,
      "rect": [95,103,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-20",
      "id": 37,
      "rect": [140,103,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-21",
      "id": 45,
      "rect": [185,103,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-22",
      "id": 53,
      "rect": [230,103,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-23",
      "id": 61,
      "rect": [275,103,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-24",
      "id": 6,
      "rect": [20,160,280,18],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-25",
      "id": 14,
      "rect": [5,146,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-26",
      "id": 22,
      "rect": [50,146,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-27",
      "id": 30,
      "rect": [95,146,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-28",
      "id": 38,
      "rect": [140,146,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-29",
      "id": 46,
      "rect": [185,146,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-30",
      "id": 54,
      "rect": [230,146,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-31",
      "id": 62,
      "rect": [275,146,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-32",
      "id": 7,
      "rect": [20,203,280,18],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-33",
      "id": 15,
      "rect": [5,189,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-34",
      "id": 23,
      "rect": [50,189,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-35",
      "id": 31,
      "rect": [95,189,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-36",
      "id": 39,
      "rect": [140,189,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-37",
      "id": 47,
      "rect": [185,189,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-38",
      "id": 55,
      "rect": [230,189,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "LTEXT",
      "content": "msnstat4-39",
      "id": 63,
      "rect": [275,189,40,12],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","WS_BORDER","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-40",
      "id": 71,
      "rect": [2,44,45,9],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-41",
      "id": 72,
      "rect": [47,44,45,9],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-42",
      "id": 73,
      "rect": [92,44,45,9],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-43",
      "id": 74,
      "rect": [137,44,45,9],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-44",
      "id": 75,
      "rect": [182,44,45,9],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-45",
      "id": 76,
      "rect": [227,44,45,9],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    },
    {
      "type": "CTEXT",
      "content": "msnstat4-46",
      "id": 77,
      "rect": [272,44,45,9],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    }
  ]
}

=== clever-play-ua/StarCraft-Remastered-UA/004_REMASTERED_FILES_TO_LOCALISE/locales/ruRU/Assets/rez/wait.ui.json
{
  "type": "DIALOG",
  "name": "Wait",
  "rect": [176,144,288,128],
  "style": ["DS_MODALFRAME","WS_POPUP","WS_SYSMENU"],
  "children": [
    {
      "type": "CTEXT",
      "content": "wait-1",
      "id": 1,
      "rect": [6,4,276,120],
      "flags": ["WS_CHILD","WS_VISIBLE","WS_GROUP","RC_BIGTEXT"],
      "children": null
    }
  ]
}
